name: Test

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    paths:
      - '**/*.ts'
      - '**/*.vue'
      - 'tsconfig*.json'
      - 'jest.config.js'
      - 'package-lock.json'
    branches:
      - main

jobs:
  unit:
    if: github.event.pull_request.draft == false
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Install
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
          node-version: 15
      - name: Install
        run: npm ci

      - name: Tests
        run: IS_CI=true npm run test -- --coverage

      - name: Test Report
        if: ${{ success() || failure() }}
        uses: dorny/test-reporter@v1
        with:
          name: JEST Tests
          path: coverage/clover.xml
          reporter: jest-junit
