name: Test

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    paths:
      - '**/*.ts'
      - '**/*.vue'
      - 'tsconfig*.json'
      - 'jest.config.js'
      - 'package-lock.json'
    branches:
      - main

jobs:
  unit:
    if: github.event.pull_request.draft == false
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - uses: actions/cache@v2
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-

      - name: Install
        run: npm ci

      - name: Tests
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "JEST_JUNIT_CLASSNAME='{classname}' JEST_JUNIT_TITLE='{title}' npx jest --forceExit --detectOpenHandles --ci --reporters=default --reporters=jest-junit"

      - name: Test Report
        if: ${{ success() || failure() }}
        uses: dorny/test-reporter@v1
        with:
          name: JEST Tests
          path: junit.xml
          reporter: jest-junit
